CinemaFlixManager/Models/ShowTimeViewModel/AddShowTimeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CinemaFlixManager.Models.ShowTimeViewModel
{
    public class AddShowTimeViewModel
    {
        [Required]
        public long MovieId { get; set; }

        [Required]
        public long CinemaId { get; set; }

        [Required]
        public string ShowingDates { get; set; }

        [Required]
        public string ShowingTimes { get; set; }
    }
}

CinemaFlixManager/Controllers/CinemasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CinemaFlixManager.Data;
using CinemaFlixManager.Models;

namespace CinemaFlixManager.Controllers
{
    public class CinemasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CinemasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Cinemas
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Cinemas.Include(c => c.CinemaState);
            ViewData["CinemaStatesId"] = new SelectList(_context.CinemaStates, "Id", "Name");
            return View(await applicationDbContext.Include(m => m.CinemaState).ToListAsync());
        }

        public async Task<IActionResult> List()
        {
            var applicationDbContext = _context.Cinemas.Include(c => c.CinemaState);
            ViewData["CinemaStatesId"] = new SelectList(_context.CinemaStates, "Id", "Name");
            var cinemas = await applicationDbContext.Include(m => m.CinemaState).ToListAsync();

            return PartialView("_List", cinemas);
        }

        // GET: Cinemas/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cinema = await _context.Cinemas
                .Include(c => c.CinemaState)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (cinema == null)
            {
                return NotFound();
            }

            return View(cinema);
        }

        // GET: Cinemas/Create
        public IActionResult Create()
        {
            ViewData["CinemaStatesId"] = new SelectList(_context.CinemaStates, "Id", "Name");
            ViewData["Cinema"] = new Cinema();
            return View();
        }

   

        // POST: Cinemas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,LogoPath,WebsiteUrl,IsActive,Address,City,CinemaStatesId")] Cinema cinema)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cinema);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CinemaStatesId"] = new SelectList(_context.CinemaStates, "Id", "Id", cinema.CinemaStatesId);
            return View(cinema);
        }

        // GET: Cinemas/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cinema = await _context.Cinemas.SingleOrDefaultAsync(m => m.Id == id);
            if (cinema == null)
            {
                return NotFound();
            }
            ViewData["CinemaStatesId"] = new SelectList(_context.CinemaStates, "Id", "Id", cinema.CinemaStatesId);
            return View(cinema);
        }

        // POST: Cinemas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name,LogoPath,WebsiteUrl,IsActive,Address,City,CinemaStatesId")] Cinema cinema)
        {
            if (id != cinema.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cinema);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CinemaExists(cinema.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CinemaStatesId"] = new SelectList(_context.CinemaStates, "Id", "Id", cinema.CinemaStatesId);
            return View(cinema);
        }

        // GET: Cinemas/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cinema = await _context.Cinemas
                .Include(c => c.CinemaState)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (cinema == null)
            {
                return NotFound();
            }

            return View(cinema);
        }

        // POST: Cinemas/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(long id)
        //{
        //    var cinema = await _context.Cinemas.SingleOrDefaultAsync(m => m.Id == id);
        //    _context.Cinemas.Remove(cinema);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        [HttpDelete, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var cinema = await _context.Cinemas.SingleOrDefaultAsync(m => m.Id == id);
            _context.Cinemas.Remove(cinema);
            await _context.SaveChangesAsync();
            return Ok("Deleted");
        }

        [HttpPut, ActionName("ChangeStatus")]
        public async Task<IActionResult> ChangeStatus(long id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var cinema = await _context.Cinemas.SingleOrDefaultAsync(m => m.Id == id);
            if (cinema == null)
            {
                return NotFound();
            }

            cinema.IsActive = !cinema.IsActive;

            _context.Entry(cinema).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CinemaExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return Ok("It is success!");
        }

        private bool CinemaExists(long id)
        {
            return _context.Cinemas.Any(e => e.Id == id);
        }
    }
}

CinemaFlixManager/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CinemaFlixManager.Data;
using CinemaFlixManager.Models;
using CinemaFlixManager.Interfaces;
using Microsoft.AspNetCore.Http;
using CloudinaryDotNet.Actions;
using System.Net.Http.Headers;
using System.IO;
using CloudinaryDotNet;
using CinemaFlixManager.Models.ShowTimeViewModel;

namespace CinemaFlixManager.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MoviesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            ViewBag.showImage = false;
            var model = await _context.Movies.OrderByDescending(x => x.Id).ToListAsync();
            return View(model);
        }

        public async Task<IActionResult> List()
        {
            var model = await _context.Movies.OrderByDescending(x => x.Id).ToListAsync();

            return PartialView("_List", model);
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .SingleOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            ViewData["Movie"] = new Movie();
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Synopsis,ThumbnailUrl,TrailerUrl,IsCurrentlyShowing,ReleaseDate,CreateDate,UpdateDate")] Movie movie)
        {
            movie.CreateDate = DateTime.Now;
            movie.UpdateDate = DateTime.Now;

            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        [HttpPost]
        public IActionResult Upload(IFormFile file)
        {
            try
            {
                Stream fileStream = file.OpenReadStream();
                //filename = hostingEnv.WebRootPath + $@"\{filename}";
                var cloudinaryParams = new
                {
                    CLOUD_NAME = "dxf3lzbni",
                    API_KEY = "864775871664545",
                    API_SECRET = "9XuUadHYAieQeMiq_fvFN4egE3A"
                };
                Account account = new Account(cloudinaryParams.CLOUD_NAME, cloudinaryParams.API_KEY, cloudinaryParams.API_SECRET);
                Cloudinary cloudinary = new Cloudinary(account);
                ImageUploadParams uploadParams = new ImageUploadParams()
                {
                    File = new FileDescription(file.FileName, fileStream),

                };

                var uploadResult = cloudinary.Upload(uploadParams);

                //string url = cloudinary.Api.UrlImgUp.BuildUrl(String.Format("{0}.{1}", uploadResult.PublicId, uploadResult.Format));
                string url = cloudinary.Api.UrlImgUp.BuildUrl(uploadResult.SecureUri.ToString());
                string transformUrl = url.Substring(0, 50) + "w_100,h_150,c_fill/" + url.Substring(50);

                transformUrl = cloudinary.Api.UrlImgUp.BuildImageTag(transformUrl);

                var response = new
                {
                    url = url,
                    transformUrl = transformUrl
                };

                return Ok(response);
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

        public IActionResult CreateShowing()
        {
            ViewData["CinemaId"] = new SelectList(_context.Cinemas, "Id", "Name");
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Title");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateShowing([Bind("Id,CinemaId,MovieId,ShowingDate,ShowTime,DateCreated,DateUpdated")] MovieShowings movieShowings)
        {
            movieShowings.ShowTime = movieShowings.ShowingDate;
            movieShowings.DateCreated = DateTime.Now;
            movieShowings.DateUpdated = DateTime.Now;
            if (ModelState.IsValid)
            {
                
                _context.Add(movieShowings);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Showings), new { id = movieShowings.MovieId });
            }
            ViewData["CinemaId"] = new SelectList(_context.Cinemas, "Id", "Id", movieShowings.CinemaId);
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Id", movieShowings.MovieId);
            return View(movieShowings);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.SingleOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Synopsis,ThumbnailUrl,TrailerUrl,IsCurrentlyShowing,ReleaseDate,CreateDate,UpdateDate")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(Convert.ToInt32(movie.Id)))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        public async Task<IActionResult> Showings(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.SingleOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            ViewData["MovieShowings"] = new MovieShowings()
            {
                MovieId = movie.Id
            };

            ViewData["CinemaId"] = new SelectList(_context.Cinemas, "Id", "Name");
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Title");
            var showing = await _context.MovieShowings.Where(m => m.MovieId == movie.Id).OrderByDescending(m => m.ShowingDate).ToListAsync();

            ListShowTimeViewModel listShowTime = new ListShowTimeViewModel()
            {
                Movie = movie,
                MovieShowings = showing
            };
            return View(listShowTime);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeStatus(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movies = await _context.Movies.SingleOrDefaultAsync(m => m.Id == id);
            if (movies == null)
            {
                return NotFound();
            }
            try
            {
                if (movies.IsCurrentlyShowing == true)
                {
                    movies.IsCurrentlyShowing = false;
                }
                else if (movies.IsCurrentlyShowing == false)
                {
                    movies.IsCurrentlyShowing = true;
                }
                _context.Update(movies);
                await _context.SaveChangesAsync();

            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MovieExists(Convert.ToInt32(movies.Id)))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return Ok(movies);
        }

        

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .SingleOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movies.SingleOrDefaultAsync(m => m.Id == id);
            _context.Movies.Remove(movie);

CinemaFlixManager/Views/Movies/Create.cshtml
@model CinemaFlixManager.Models.Movie

@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-md-8">
       
            <div id="show-image">

            </div>
        
        <div class="form-group">
            <input id="thumbnail-upload"  type="file" class="form-control" />
            
        </div>
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Synopsis" class="control-label"></label>
                <textarea asp-for="Synopsis" class="form-control"></textarea>
                <span asp-validation-for="Synopsis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThumbnailUrl" class="control-label"></label>
                <input asp-for="ThumbnailUrl" class="form-control" />
                <span asp-validation-for="ThumbnailUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrailerUrl" class="control-label"></label>
                <input asp-for="TrailerUrl" class="form-control" />
                <span asp-validation-for="TrailerUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsCurrentlyShowing" /> @Html.DisplayNameFor(model => model.IsCurrentlyShowing)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CinemaFlixManager/Views/Movies/CreateShowing.cshtml
@model CinemaFlixManager.Models.MovieShowings

    @*<link href="~/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="~/AdminLTE/bower_components/select2/dist/css/select2.min.css">

    <div class="row">
        <div class="col-md-12">
            <form asp-action="CreateShowing">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="CinemaId" class="control-label"></label>
                    <select asp-for="CinemaId" class="form-control select2" data-placeholder="Select a Cinema" asp-items="ViewBag.CinemaId"></select>
                </div>
                <div class="form-group">
                    <input asp-for="MovieId" type="hidden" class="form-control" />
                    @*<select asp-for="MovieId" class="form-control" asp-items="ViewBag.MovieId"></select>*@
                </div>
                <div class="form-group">
                    <label asp-for="ShowingDate" class="control-label"></label>
                    <input asp-for="ShowingDate" asp-format="asp-format="{0:MM/dd/yyyy}" class="form-control" />
                    <span asp-validation-for="ShowingDate" class="text-danger"></span>
                </div>
            
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        <script src="~/AdminLTE/bower_components/select2/dist/js/select2.full.min.js"></script>
        @*<script src="~/Tags-input/tagsinput.js"></script>*@
        <script>
            //$('#reservation').daterangepicker()
            $('.select2').select2()

        </script>
    }

CinemaFlixManager/Views/Movies/Delete.cshtml
@model Test2.Models.Movie

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Synopsis)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Synopsis)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ThumbnailUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ThumbnailUrl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TrailerUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TrailerUrl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsCurrentlyShowing)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsCurrentlyShowing)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CinemaFlixManager/Views/Movies/Details.cshtml
@model CinemaFlixManager.Models.Movie

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Synopsis)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Synopsis)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ThumbnailUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ThumbnailUrl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TrailerUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TrailerUrl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsCurrentlyShowing)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsCurrentlyShowing)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CinemaFlixManager/Views/Movies/Edit.cshtml
@model CinemaFlixManager.Models.Movie

@{
    ViewData["Title"] = "Edit";
}

<div class="row">
    <div class="col-md-8">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Synopsis" class="control-label"></label>
                <textarea asp-for="Synopsis" class="form-control" ></textarea>
                <span asp-validation-for="Synopsis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThumbnailUrl" class="control-label"></label>
                <input asp-for="ThumbnailUrl" class="form-control" />
                <span asp-validation-for="ThumbnailUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrailerUrl" class="control-label"></label>
                <input asp-for="TrailerUrl" class="form-control" />
                <span asp-validation-for="TrailerUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsCurrentlyShowing" /> @Html.DisplayNameFor(model => model.IsCurrentlyShowing)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdateDate" class="control-label"></label>
                <input asp-for="UpdateDate" class="form-control" />
                <span asp-validation-for="UpdateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CinemaFlixManager/Views/Movies/Index.cshtml
@*@model IEnumerable<CinemaFlixManager.Models.Movie>*@

@{
    ViewData["Title"] = "Index";
    ViewData["Heading"] = "Movies";
}

<p class="pull-right">
    <button class="btn btn-success" data-toggle="modal" data-target="#modal-create">Create New</button>
</p>
<br />
<hr />

<!--Details-->
<div class="modal fade" id="modal-create">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Add New Cinema</h4>
            </div>
            <div class="modal-body">
                @*<p>One fine body&hellip;</p>*@
                @*@Html.Partial("Create")*@
                @await Html.PartialAsync("Create", @ViewData["Movie"])
            </div>
            @*<div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>*@
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<div id="cinemasDiv" data-url='@Url.Action("List")'>
    @Html.Partial("_List")
</div>

@section scripts{
    <script>
    $(document).ready(function () {
        $('input[type="file"]').change(function () {

            var _url = '@Url.Action("Upload", "Movies")';
            var formData = new FormData();
            formData.append('file', $('#thumbnail-upload')[0].files[0]);

            console.log("A file has been selected.");
             $.ajax({
                 url: _url,
                 method: "POST",
                 data: formData,
                 processData: false,  // tell jQuery not to process the data
                 contentType: false,  // tell jQuery not to set contentType
                    success: function (data) {
                        console.log("success");
                        console.log(data);
                        $("#ThumbnailUrl").val(data.url);
                        $("#show-image").html(data.transformUrl);
                        //var cinemasDiv = $('#cinemasDiv'),
                        //    url = $(this).data('url');

                        //$.get(url, function (data) {
                        //    cinemasDiv.html(data);
                        //});
                        //$('#cinemasDiv').load('@*@Url.Action("List","Cinemas")*@');
                        //e.preventDefault();
                    },
                })
                console.log("You clicked me");
            });

        });
    </script>
}